[package]
name = "cuboid"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0.71"
itertools = "0.10.5"

[dependencies.fj-kernel]
path = "../../crates/fj-kernel"

[dependencies.fj-math]
path = "../../crates/fj-math"

[dependencies.fj-window]
path = "../../crates/fj-window"
