[workspace]
resolver = "2"
members = [
    "crates/fj-export",
    "crates/fj-interop",
    "crates/fj-kernel",
    "crates/fj-math",
    "crates/fj-viewer",
    "crates/fj-window",

    "models/cuboid",

    "tools/autolib",
    "tools/automator",
    "tools/cross-compiler",
    "tools/export-validator",
    "tools/release-operator",
]
default-members = [
    "crates/fj-export",
    "crates/fj-interop",
    "crates/fj-kernel",
    "crates/fj-math",
    "crates/fj-viewer",
]


[workspace.package]
version = "0.46.0"
edition = "2021"

description = "Early-stage b-rep CAD kernel."
readme = "README.md"
homepage = "https://www.fornjot.app/"
repository = "https://github.com/hannobraun/fornjot"
license = "0BSD"
keywords = ["cad", "programmatic", "code-cad"]
categories = ["encoding", "mathematics", "rendering"]


[workspace.dependencies.fj]
version = "0.46.0"
path = "crates/fj"

[workspace.dependencies.fj-export]
version = "0.46.0"
path = "crates/fj-export"

[workspace.dependencies.fj-host]
version = "0.46.0"
path = "crates/fj-host"

[workspace.dependencies.fj-interop]
version = "0.46.0"
path = "crates/fj-interop"

[workspace.dependencies.fj-kernel]
version = "0.46.0"
path = "crates/fj-kernel"

[workspace.dependencies.fj-math]
version = "0.46.0"
path = "crates/fj-math"

[workspace.dependencies.fj-operations]
version = "0.46.0"
path = "crates/fj-operations"

[workspace.dependencies.fj-proc]
version = "0.46.0"
path = "crates/fj-proc"

[workspace.dependencies.fj-viewer]
version = "0.46.0"
path = "crates/fj-viewer"
