[workspace]
resolver = "2"
members = [
    "crates/fj",
    "crates/fj-app",
    "crates/fj-export",
    "crates/fj-host",
    "crates/fj-interop",
    "crates/fj-kernel",
    "crates/fj-math",
    "crates/fj-operations",
    "crates/fj-viewer",
    "crates/fj-proc",

    "crates/fj-window",

    "crates/fj-proc",


    "models/cuboid",
    "models/spacer",
    "models/star",
    "models/star_attributed_arguments",
    "models/test",

    "tools/export-validator",
    "tools/release-operator",
]
default-members = [
    "crates/fj-app",
    "crates/fj-export",
    "crates/fj-host",
    "crates/fj-interop",
    "crates/fj-kernel",
    "crates/fj-math",
    "crates/fj-operations",
    "crates/fj-viewer",
    "crates/fj-window",
]
