[package]
name    = "fj-host"
version = "0.4.0"
edition = "2021"


[dependencies]
anyhow      = "*"
bytemuck    = "*"
decorum     = "*"
delaunator  = "*"
futures     = "*"
libloading  = "*"
nalgebra    = "*"
notify      = "5.0.0-pre.13"
parry3d-f64 = "*"
thiserror   = "*"
threemf     = "*"
tracing     = "*"
# TASK: Upgrade, once `wgpu_glyph` has been updated.
wgpu        = "0.11.1"
wgpu_glyph  = "*"
winit       = "*"

[dependencies.clap]
version  = "3.0.0-rc.1"
features = ["derive"]

[dependencies.fj]
path = "fj"
