[package]
name    = "fj-host"
version = "0.3.1"
edition = "2021"


[dependencies]
anyhow      = "*"
bytemuck    = "*"
clap        = "3.0.0-beta.5"
decorum     = "*"
delaunator  = "*"
futures     = "*"
libloading  = "*"
nalgebra    = "*"
notify      = "5.0.0-pre.13"
parry3d-f64 = "*"
thiserror   = "*"
threemf     = "*"
tracing     = "*"
wgpu        = "*"
wgpu_glyph  = "*"
winit       = "*"

[dependencies.fj]
path = "fj"


# TASK: Remove this, once a new release of `wgpu_glyph` is out. See this issue
#       for context: https://github.com/hecrj/wgpu_glyph/issues/81
[patch.crates-io.wgpu_glyph]
git = "https://github.com/hecrj/wgpu_glyph.git"
