[package]
name    = "fj-host"
version = "0.4.0"
edition = "2021"


[dependencies]
anyhow      = "*"
bytemuck    = "*"
decorum     = "*"
delaunator  = "*"
futures     = "*"
libloading  = "*"
nalgebra    = "*"
notify      = "5.0.0-pre.13"
parry2d-f64 = "*"
parry3d-f64 = "*"
thiserror   = "*"
threemf     = "*"
tracing     = "*"
wgpu        = "*"
wgpu_glyph  = "*"
winit       = "*"

[dependencies.clap]
version  = "*"
features = ["derive"]

[dependencies.fj]
version = "0.4.0"
path    = "fj"
