[workspace]
resolver = "2"
members = [
    "fj",
    "fj-app",
    "fj-host",
    "fj-interop",
    "fj-kernel",
    "fj-math",
    "fj-operations",

    "models/cuboid",
    "models/group",
    "models/spacer",
    "models/star",

    "release-operator",
]
default-members = [
    "fj-app",
    "fj-host",
    "fj-interop",
    "fj-kernel",
    "fj-math",
    "fj-operations",
]
