# The default path that models are loaded from. If the `model` argument is a
# relative path, it is assumed to be relative to `default_path`.
default_path = "models"

# The default models that is loaded, if none is specified in a CLI.
# If this is a relative path, it should be relative to `default_path`.
default_model = "test"

# Indicate whether to invert the zoom direction. Can be used to override the
# OS-level setting.
invert_zoom = false
