[package]
name = "fj-operations"
version = "0.5.0"
edition = "2021"

description = "The world needs another CAD program."
readme = "../README.md"
repository = "https://github.com/hannobraun/fornjot"
license = "0BSD"
keywords = ["cad", "programmatic", "code-cad"]
categories = ["mathematics"]


[dependencies.fj]
version = "0.5.0"
path = "../fj"

[dependencies.fj-math]
version = "0.5.0"
path = "../fj-math"

[dependencies.fj-interop]
version = "0.5.0"
path = "../fj-interop"

[dependencies.fj-kernel]
version = "0.5.0"
path = "../fj-kernel"
