[package]
name = "fj-window"
version.workspace = true
edition.workspace = true
description.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
futures = "0.3.24"
thiserror = "1.0.35"
tracing = "0.1.35"
winit = "0.27.3"

[dependencies.fj-host]
version = "0.16.0"
path = "../fj-host"

[dependencies.fj-operations]
version = "0.16.0"
path = "../fj-operations"

[dependencies.fj-viewer]
version = "0.16.0"
path = "../fj-viewer"

[dependencies.fj-interop]
version = "0.16.0"
path = "../fj-interop"
