[package]
name = "fj"
version.workspace = true
edition.workspace = true
description.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
serde = { version = "1.0.144", features = ["derive"], optional = true }

[dependencies.fj-proc]
version = "0.16.0"
path = "../../crates/fj-proc"

[dev-dependencies]
serde_json = "1.0.85"
