[package]
name    = "spacer2"
version = "0.1.0"
authors = ["Hanno Braun <hanno@braun-odw.eu>"]
edition = "2021"
publish = false


[dependencies]
anyhow = "*"
serde  = "*"

[dependencies.fj]
path = "../../fj"
