[package]
name    = "fj"
version = "0.1.0"
authors = ["Hanno Braun <hanno@braun-odw.eu>"]
edition = "2018"

description = "Experimental CAD system"
readme      = "../README.md"
repository  = "https://github.com/hannobraun/fornjot"
license     = "0BSD"
keywords    = ["cad", "programmatic", "constructive", "solid", "geometry"]
categories  = ["mathematics", "rendering"]


[dependencies]
bytemuck           = "1.5.1"
decorum            = "0.3.1"
futures            = "0.3.15"
itertools          = "0.10.0"
nalgebra           = "0.26.2"
tracing            = "0.1.26"
tracing-subscriber = "0.2.18"
wgpu               = "0.8.1"
winit              = "0.25.0"
