[package]
name    = "fj"
version = "0.1.0"
authors = ["Hanno Braun <hanno@braun-odw.eu>"]
edition = "2018"

[dependencies]
approx             = "*"
bytemuck           = "*"
decorum            = "*"
futures            = "*"
itertools          = "*"
nalgebra           = "*"
num-traits         = "*"
shaderc            = "*"
thiserror          = "*"
tracing            = "*"
tracing-subscriber = "*"
wgpu               = "*"
winit              = "*"
