[package]
name    = "fj"
version = "0.3.1"
edition = "2021"

description = "Experimental CAD system"
readme      = "../README.md"
repository  = "https://github.com/hannobraun/fornjot"
license     = "0BSD"
keywords    = ["cad", "programmatic", "code-cad"]
categories  = ["mathematics", "rendering"]
