[package]
name    = "fj"
version = "0.1.0"
authors = ["Hanno Braun <hb@hannobraun.de>"]
edition = "2018"

[dependencies]
approx     = "*"
bytemuck   = "*"
decorum    = "*"
futures    = "*"
nalgebra   = "*"
# TASK: Upgrade to Parry
ncollide2d = "*"
parry2d    = "*"
rand       = "*"
shaderc    = "*"
wgpu       = "*"
winit      = "*"
