[package]
name = "release-operator"
version = "0.3.1"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
cargo_metadata = "0.14.2"
cmd_lib = "1.3.0"
env_logger = "0.9.0"
log = "0.4.17"
regex = "1.5.6"
secstr = "0.5.0"
semver = "1.0.10"
serde_json = "1.0.81"

[dependencies.reqwest]
version = "0.11.10"
features = ["blocking"]

[dependencies.clap]
version = "3.1.18"
features = ["std", "derive", "env"]
default_features = false

[dependencies.serde]
version = "1.0.137"
features = ["derive"]
