[package]
name = "fj-viewer"
version.workspace = true
edition.workspace = true
description.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
bytemuck = "1.12.1"
fj-interop.workspace = true
fj-math.workspace = true
raw-window-handle = "0.4.3"
thiserror = "1.0.35"
tracing = "0.1.35"
wgpu = "0.13.1"
wgpu_glyph = "0.17.0"

[dependencies.egui]
version = "0.19.0"

[dependencies.egui-wgpu]
version = "0.19.0"
features = ["winit"]

[dependencies.egui-winit]
version = "0.19.0"
