[package]
name = "fj-host"
version = "0.5.0"
edition = "2021"

description = "The world needs another CAD program."
readme = "../README.md"
repository = "https://github.com/hannobraun/fornjot"
license = "0BSD"
keywords = ["cad", "programmatic", "code-cad"]
categories = ["encoding", "mathematics", "rendering"]


[dependencies]
libloading = "0.7.2"
notify = "5.0.0-pre.15"
thiserror = "1.0.31"

[dependencies.fj]
version = "0.5.0"
path = "../fj"
