[package]
name = "fj-app"
version.workspace = true
edition.workspace = true
description.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true


[dependencies]
anyhow = "1.0.65"

[dependencies.clap]
version = "3.2.22"
features = ["derive"]

[dependencies.figment]
version = "0.10.6"
features = ["env", "toml"]

[dependencies.fj]
version = "0.16.0"
path = "../fj"

[dependencies.fj-export]
version = "0.16.0"
path = "../fj-export"

[dependencies.fj-host]
version = "0.16.0"
path = "../fj-host"

[dependencies.fj-interop]
version = "0.16.0"
path = "../fj-interop"

[dependencies.fj-kernel]
version = "0.16.0"
path = "../fj-kernel"

[dependencies.fj-math]
version = "0.16.0"
path = "../fj-math"

[dependencies.fj-operations]
version = "0.16.0"
path = "../fj-operations"

[dependencies.fj-viewer]
version = "0.16.0"
path = "../fj-viewer"

[dependencies.fj-window]
version = "0.16.0"
path = "../fj-window"

[dependencies.serde]
version = "1.0.144"
features = ["derive"]

[dependencies.tracing-subscriber]
version = "0.3.15"
features = ["env-filter", "fmt"]
