[package]
name = "fj-app"
version.workspace = true
edition.workspace = true
description.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[build-dependencies.ignore]
version = "0.4.18"
default-features = false

[build-dependencies.tar]
version = "0.4.35"
default-features = false

[dependencies]
anyhow = "1.0.66"
fj.workspace = true
fj-export.workspace = true
fj-host.workspace = true
fj-interop.workspace = true
fj-kernel.workspace = true
fj-math.workspace = true
fj-operations.workspace = true
fj-viewer.workspace = true
fj-window.workspace = true
include_dir = "0.7.3"

[dependencies.clap]
version = "4.0.23"
features = ["derive", "string"]

[dependencies.figment]
version = "0.10.8"
features = ["env", "toml"]

[dependencies.serde]
version = "1.0.147"
features = ["derive"]

[dependencies.tracing-subscriber]
version = "0.3.16"
features = ["env-filter", "fmt"]

[dependencies.tar]
version = "0.4.35"
default-features = false
