name: Compile Binaries

on:
  push:
    branches: [ main, '#57_do-not-compress-binaries' ]

env:
  CARGO_TERM_COLOR: always

  # Name of the crate from Cargo.toml
  # used to rename and upload the binaries
  PROJ_NAME: fj-host

jobs:
  binaries:
    name: Binaries
    strategy:
      matrix:
        include:
          # Supported `cross` targets:
          #   https://github.com/rust-embedded/cross#supported-targets

          # Linux targets
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest, cross: true }
          - { target: x86_64-unknown-linux-musl, os: ubuntu-latest, cross: true }
          - { target: aarch64-unknown-linux-musl, os: ubuntu-latest, cross: true }

          # macOS targets
          - { target: x86_64-apple-darwin, os: macOS-latest, cross: false }
          - { target: aarch64-apple-darwin, os: macOS-latest, cross: false }

          # Windows works
          - { target: x86_64-pc-windows-msvc, os: windows-latest, cross: false }

    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Toolchain
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          target: ${{ matrix.target }}
          toolchain: stable

      - name: Cache
        uses: Swatinem/rust-cache@v1

      - name: Compile
        uses: actions-rs/cargo@v1
        with:
          args: --release --target ${{ matrix.target }}
          command: build
          use-cross: ${{ matrix.cross }}

      - name: Prepare Upload
        shell: bash
        run: |
          # Include compile target in binary name
          
          mv -v \
            "target/${{ matrix.target }}/release/${PROJ_NAME}" \
            "${GITHUB_WORKSPACE}/${PROJ_NAME}-${{ matrix.target }}"
          
          chmod -v +x \
            "${GITHUB_WORKSPACE}/${PROJ_NAME}-${{ matrix.target }}"

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJ_NAME }}-${{ matrix.target }}
          path: ${{ env.PROJ_NAME }}-${{ matrix.target }}
