name: Binaries

on:
  push:
    branches: [ main, '#57_provide-major-os-binaries-for-every-commit-to-main' ]

env:
  CARGO_TERM_COLOR: always

  # Name of the crate from Cargo.toml
  # used to package up the binaries on disk
  PROJ_NAME: fj-host

jobs:
  binaries:
    name: Binaries
    strategy:
      matrix:
        include:
          # Supported `cross` targets:
          #   https://github.com/rust-embedded/cross#supported-targets

          # Linux targets
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest, cross: true }
          - { target: x86_64-unknown-linux-musl, os: ubuntu-latest, cross: true }
          - { target: aarch64-unknown-linux-musl, os: ubuntu-latest, cross: true }

          # macOS targets
          - { target: x86_64-apple-darwin, os: macOS-latest, cross: false }
          - { target: aarch64-apple-darwin, os: macOS-latest, cross: false }

          # Windows works
          - { target: x86_64-pc-windows-msvc, os: windows-latest, cross: false }

    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Toolchain
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          target: ${{ matrix.target }}
          toolchain: stable

      - name: Cache
        uses: Swatinem/rust-cache@v1

      - name: Compile
        uses: actions-rs/cargo@v1
        with:
          args: --release --target ${{ matrix.target }}
          command: build
          use-cross: ${{ matrix.cross }}

      - name: Compress
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          case "${RUNNER_OS}" in
            Linux)
              tar czvf "${GITHUB_WORKSPACE}/${PROJ_NAME}-${{ matrix.target }}.tar.gz" "${PROJ_NAME}"
              ;;
            macOS)
              # gh docs say gtar is aliased to tar, but it failed
              gtar czvf "${GITHUB_WORKSPACE}/${PROJ_NAME}-${{ matrix.target }}.tar.gz" "${PROJ_NAME}"
              ;;
            Windows)
              7z a "${GITHUB_WORKSPACE}/${PROJ_NAME}-${{ matrix.target }}.zip" "${PROJ_NAME}.exe"
              ;;
            *)
              echo "[ERROR] unsupported OS: ${RUNNER_OS}"
              exit 1
          esac
          cd -

      - name: Upload Unix
        if: runner.os != 'Windows'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJ_NAME }}-${{ matrix.target }}.tar.gz
          path: ${{ env.PROJ_NAME }}-${{ matrix.target }}.tar.gz

      - name: Upload Windows
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJ_NAME }}-${{ matrix.target }}.zip
          path: ${{ env.PROJ_NAME }}-${{ matrix.target }}.zip
